apiVersion: v1
kind: Namespace
metadata:
  labels:
    pgo-created-by: githubcicd
    pgo-installation-name: devtest
    vendor: crunchydata
  name: $KUB_TEMP_PREFIX-namespace
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $KUB_TEMP_PREFIX-role
  namespace: $KUB_TEMP_PREFIX-namespace
rules:
- apiGroups: ["", "elasticsearch.k8s.elastic.co", "kibana.k8s.elastic.co", "crunchydata.com", "extensions", "apps"]
  resources: ["services", "secrets", "elasticsearches", "kibanas", "pgclusters", "pgreplicas" , "ingresses", "deployments", "deployments/scale", "statefulsets", "statefulsets/scale"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: $KUB_TEMP_PREFIX-user
  namespace: $KUB_TEMP_PREFIX-namespace
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $KUB_TEMP_PREFIX-rolebinding
  namespace: $KUB_TEMP_PREFIX-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $KUB_TEMP_PREFIX-role
subjects:
- kind: ServiceAccount
  name: $KUB_TEMP_PREFIX-user
  namespace: $KUB_TEMP_PREFIX-namespace
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $KUB_TEMP_PREFIX-nginx-role
  namespace: $KUB_TEMP_PREFIX-namespace
rules:
  - apiGroups: ["", "apps"]
    resources: ["configmaps", "deployments"]
    verbs: ["get", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $KUB_TEMP_PREFIX-nginx-rolebinding
  namespace: $NGINX_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $KUB_TEMP_PREFIX-nginx-role
subjects:
  - kind: ServiceAccount
    name: $KUB_TEMP_PREFIX-user
    namespace: $KUB_TEMP_PREFIX-namespace
