apiVersion: v1
kind: Namespace
metadata:
  name: $KUB_TEMP_PREFIX-namespace
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $KUB_TEMP_PREFIX-role
  namespace: $KUB_TEMP_PREFIX-namespace
rules:
- apiGroups: ["", "elasticsearch.k8s.elastic.co"] 
  resources: ["pods", "namespaces", "deployments", "services", "apps", "persistentvolumes", "elasticsearches"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: $KUB_TEMP_PREFIX-user
  namespace: $KUB_TEMP_PREFIX-namespace
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $KUB_TEMP_PREFIX-rolebinding
  namespace: $KUB_TEMP_PREFIX-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $KUB_TEMP_PREFIX-role
subjects:
- kind: ServiceAccount
  name: $KUB_TEMP_PREFIX-user
  namespace: $KUB_TEMP_PREFIX-namespace