apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {opa.random.name}
  namespace: {opa.user.namespace}
spec:
  version: 7.10.2
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        path.repo: ["/usr/share/elasticsearch/backups"]