apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: {opa.random.name[0]}
  labels:
    crunchy-pgha-scope: {opa.random.name[0]}
    deployment-name: {opa.random.name[0]}
    name: {opa.random.name[0]}
    pg-cluster: {opa.random.name[0]}
    pgo-version: 4.6.1
    pgouser: admin
  name: {opa.random.name[0]}
  namespace: {opa.user.namespace}
spec:
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: {opa.random.name[0]}
    size: 1G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  annotations: {}
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos8-13.2-4.6.1
  clustername: {opa.random.name[0]}
  database: {opa.random.name[0]}
  exporterport: "9187"
  limits: {}
  name: {opa.random.name[0]}
  namespace: {opa.user.namespace}
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  port: "5432"
  tolerations: []
  user: hippo
  userlabels:
    pgo-version: 4.6.1