apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ""
  namespace: ""
spec:
  version: 7.10.2
  nodeSets:
    - name: default
      count:
      config:
        node.store.allow_mmap: false