// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package api

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts/login": {
            "post": {
                "description": "Get login token and role by providing username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Account credentials",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.AccountCredentialsDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.AuthenticationResponseDataDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        },
        "/services/action/{servicetype}/{servicename}/{actioncommand}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Apply a service specific action to a service instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "Apply a service specific action to a service instance",
                "parameters": [
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Type of service",
                        "name": "servicetype",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Id of service",
                        "name": "servicename",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "action command",
                        "name": "actioncommand",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ServiceInstanceActionResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        },
        "/services/create/{servicetype}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create an instance of a service from yaml",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "Create service instance from yaml",
                "parameters": [
                    {
                        "description": "Service-Yaml",
                        "name": "serviceyaml",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.ServiceYamlDto"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Type of service",
                        "name": "servicetype",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        },
        "/services/info": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get an overview over all service instances",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "Get an overview over all service instances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ServiceInstanceDetailsOverviewDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        },
        "/services/info/{servicetype}/{servicename}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get details over a single service instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "Get details over a single service instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of service",
                        "name": "servicetype",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Id of service",
                        "name": "servicename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ServiceInstanceDetailsOverviewDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        },
        "/services/yaml/{servicetype}/{servicename}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the yaml file for an specific service instance. Parameter servicename has to be supplied.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "Get the yaml file for an instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of service",
                        "name": "servicetype",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Id of service",
                        "name": "servicename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ServiceYamlDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        },
        "/services/{servicetype}/{servicename}": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Delete an instance of a service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "Delete a service instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of service",
                        "name": "servicetype",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Id of service",
                        "name": "servicename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        },
        "/servicestore/form/{servicetype}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the default yaml file for a service-template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servicestore"
                ],
                "summary": "Get the json form for a service-template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of service",
                        "name": "servicetype",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ServiceStoreItemFormDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        },
        "/servicestore/info": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Lists all possible deployable services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servicestore"
                ],
                "summary": "Lists all possible deployable services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ServiceStoreOverviewDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        },
        "/servicestore/yaml/{servicetype}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the yaml for a service based on the filled form and the user data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servicestore"
                ],
                "summary": "Get the yaml for a service",
                "parameters": [
                    {
                        "description": "Form-Result",
                        "name": "formresult",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Type of service",
                        "name": "servicetype",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ServiceStoreItemYamlDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.HTTPErrorDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.AccountCredentialsDto": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "masterkey"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dtos.AuthenticationResponseDataDto": {
            "type": "object",
            "properties": {
                "isValid": {
                    "type": "boolean",
                    "example": true
                },
                "role": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dtos.HTTPErrorDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        },
        "dtos.ServiceInstanceActionDto": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "example": "cmdExpose"
                },
                "form": {
                    "type": "string",
                    "example": "ngx json form valid data"
                },
                "isToggle": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "Expose service"
                }
            }
        },
        "dtos.ServiceInstanceActionGroupDto": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ServiceInstanceActionDto"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Security"
                }
            }
        },
        "dtos.ServiceInstanceActionResponseDto": {
            "type": "object",
            "properties": {
                "resultJson": {
                    "type": "string",
                    "example": "{\"MyJsonObj\": \"Value\"}"
                }
            }
        },
        "dtos.ServiceInstanceDetailsDto": {
            "type": "object",
            "properties": {
                "actionGroups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ServiceInstanceActionGroupDto"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "my_kibana_instance_1"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "type": {
                    "type": "string",
                    "example": "kibana"
                }
            }
        },
        "dtos.ServiceInstanceDetailsOverviewDto": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ServiceInstanceDetailsDto"
                    }
                }
            }
        },
        "dtos.ServiceStoreItemDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Dashboard for elasticsearch"
                },
                "imageSource": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAA/hNdgD"
                },
                "type": {
                    "type": "string",
                    "example": "kibana"
                }
            }
        },
        "dtos.ServiceStoreItemFormDto": {
            "type": "object",
            "properties": {
                "formJson": {
                    "type": "string",
                    "example": "{\"MyJsonObj\": \"Value\"}"
                }
            }
        },
        "dtos.ServiceStoreItemYamlDto": {
            "type": "object",
            "properties": {
                "yaml": {
                    "type": "string",
                    "example": "item: text"
                }
            }
        },
        "dtos.ServiceStoreOverviewDto": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ServiceStoreItemDto"
                    }
                }
            }
        },
        "dtos.ServiceYamlDto": {
            "type": "object",
            "properties": {
                "yaml": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "x-extension-openapi": {
        "example": "value on a json format"
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{"https"},
	Title:       "Operator Automation Backend API",
	Description: "Operator Automation Backend API overview.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
