name: Go

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:



      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Prepare new remote cluster user
        run: |
          cd .github
          (printf KUB_TEMP_PREFIX=github; (tr -dc a-z </dev/urandom | head -c 13 ; echo '')) >> $GITHUB_ENV
          echo $KUB_TEMP_PREFIX
          ls -al
          cp create_service_account.yaml create_service_account_temp.json
          envsubst < create_service_account_temp.json > create_service_account.yaml
          rm create_service_account_temp.json
          cat create_service_account.json
          cd ..

