name: Go

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Prepare new remote cluster user
        run: |
          cd .github
          printf github > randomuser.txt
          head -1 <(fold -w 20  <(tr -dc 'a-z' < /dev/urandom)) >> randomuser.txt
          export KUB_TEMP_PREFIX=`cat randomuser.txt`
          echo $KUB_TEMP_PREFIX
          cp create_service_account.yaml create_service_account_temp.yaml
          envsubst < create_service_account_temp.yaml > create_service_account.yaml
          rm create_service_account_temp.yaml
          cat create_service_account.yaml
          cd ..

      - name: Write .kubeconfig to file
        run: |
          echo $KUBECONFIG | base64 -di > kubeconfig
          mv kubeconfig $HOME/.kube/config
          kubectl get pods --all-namespaces
        env:
          KUBECONFIG: ${{ secrets.GH_KUBE_CONFIG }}

      - name: Test
        run: |
          echo $KUB_TEMP_PREFIX